### ISSUE TITLE
Display allergies on the patient summary header

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#235]
Once we have #234, display allergies in the patient summary component (app/components/patient-summary.js).
## TODO
- [ ] Ability to specify allergies for a patient
  - [x] Modify the model to add allergies hasMany
  - [ ] Change Visits edit route to allow editing allergies
  - [ ] Display on Patient Summary

**Comment by jkleinsc** [comment]
Since part of this issue is to Change Visits edit route to allow editing allergies, I suggest what happens is that there is a way to edit the allergies directly in the patient summary header when on the visit screen versus having separate fields on the visit form to collect allergies.

**Comment by donaldwasserman** [comment]
I'm taking a stab at this as well, but would it be better to do this on the patient information view or the visit view? 

(I only say that because I just added it on the patient information screen, but it can be an easy copy and paste over)

**Comment by jkleinsc** [comment]
@donaldwasserman it should be added to the patient summary component: 
https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/templates/components/patient-summary.hbs

This component displays on both the patient screen as well as the visit screen.

The allergies need to be editable from the visit screen, but making it editable on the patient screen is probably a good idea too.

**Comment by donaldwasserman** [comment]
I have the stuff setup as a component to jam in wherever. 

@jkleinsc I'll have some stuff I want you to look at this week. (Day care-related illnesses cut back on some of my available time/willingness this weekend). It's not going to be finished, but want to get some feedback to make sure I haven't gotten too far afield. 

What's the best way to share some of that code with you?

**Comment by jkleinsc** [comment]
Thanks @donaldwasserman... sorry about the illnesses... sick kids are no fun!  

As far as sharing the code, just create a pull request but specifically state that it is in progress (I'll add a label as well), so that it doesn't accidentally get merged in.  Github PR's now have a nice review process so we can use that as well if you put in in a PR.
