### ISSUE TITLE
[TRACKING ISSUE] Button styles are inconsistent at best, and ineffective and confusing at worst

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#359]
**TRACKING LIST:**
- [x] #346 Second cta button on billing page has wrong text color
- [ ] #313 Button not visible properly
- [x] #360 Primary call to action buttons should be right aligned, secondary buttons beside it to the left

**Expected experience:** Button styles in the app should be consistent, and should help indicate what their function is.

**Actual experience:** Button styles are wildly inconsistent, and often very confusing. For example: 
- The styles for disabled buttons do not clearly convey that they are disabled. 
- Hover states are unhelpful and confusing (some buttons get darker on hover, some get lighter on hover, and others change color entirely on hover). 
- In some places buttons are inconsistent in width.
- Where there should be only one primary call to action, in some places there are up to three.
- Alignment of buttons is inconsistent (in some views they are left aligned, while in others they are right aligned)

**Screenshots:**

![hospitalrun-buttons](https://cloud.githubusercontent.com/assets/1319791/13812755/2be24eae-eb3b-11e5-896e-c5285a3be54f.gif)

![image](https://cloud.githubusercontent.com/assets/1319791/13812706/ecd0e4be-eb3a-11e5-9c66-f37c61a07262.png)

![image](https://cloud.githubusercontent.com/assets/1319791/13812719/fb185d22-eb3a-11e5-9fa9-6a6d69deffe8.png)

**Comment by jglovier** [comment]
Interesting idea from @dswanson via https://github.com/HospitalRun/hospitalrun-frontend/issues/361#issuecomment-197405916

>Another affordance I have seen work is to de-emphasize the actions except when the specific row has focus.

>When the user "selects" the row, that row is highlighted and then the actions are made more apparent.
This can be done by making the actions invisible until the highlighting, or just changing their opacity.

**Comment by tangollama** [comment]
@jglovier is this still relevant? If so, can we make it a HackDay issue?

**Comment by aayushsanghavi** [comment]
Sir, I would like to take up this issue. I am new to open source so your guidance would be appreciated.
Could you tell me where to start from and which files have these issues.

**Comment by jkleinsc** [comment]
@aayushsanghavi thank you for your interest.  I believe this issue was mislabeled for hacktoberfest as I'm not sure there is anything to do here.

@jglovier isn't this a tracking issue vs a specific issue that folks can work on?  Not sure why it has the hacktoberfest label on it.

**Comment by Lily418** [comment]
Looks like the final item in the checklist has been closed by #983 I think this can now be closed?

**Comment by donaldwasserman** [comment]
@Lily418 Thanks, looks good.
