### ISSUE TITLE
[TRACKING ISSUE] Clean up edit patient view design

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#378]
The edit patient view has a ton of design issues.
- [x] Patient summary styling doesn't match anything in the app (#379; fixed in #385)
- [x] Patient summary doesn't display any helpful hierarchy of information (#379; fixed in #385)
- [x] The tab styling is default bootstrap styling and doesn't match the app (fixed in #385)
- [x] Input sections needs improved spacing and typography (fixed in #385)
- [ ] Sections with a section heading, button, and table below need style help
- [ ] Call to action buttons in general need help (see #359)

**Current design:**

![image](https://cloud.githubusercontent.com/assets/1319791/13894830/89a78e2e-ed29-11e5-9a87-bfb4892095d6.png)

**Better design:**

![image](https://cloud.githubusercontent.com/assets/1319791/13894838/9541db0e-ed29-11e5-9718-e408679beade.png)
