### ISSUE TITLE
Data issues with deletions

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#383]
My system has a patient document that is completely deleted. That delete didn't cascade to things like the imaging request queue. As a result, my imaging index route isn't rendering. We need several changes:

- [x] cascading deletes for true deletions of patients #380
- [x] flagging deletions of patients as "archived" status, as well as excluding that status from views #381
- [x] better error handling for deletions in edit and index routes, such that data issues like this won't tank the system #382

**Expected behavior:**
Imaging index route renders, regardless of data issues.

**Actual behavior:**
Error.

Console is producing the following error message.

Error while processing route: imaging.index Assertion Failed: You looked up the 'patient' relationship on a 'imaging' with id 6C16C18A-1FCE-35A0-9777-47DD2F55C957 but some of the associated records were not loaded. Either make sure they are all loaded together with the parent record, or specify that the relationship is async (`DS.belongsTo({ async: true })`) Error: Assertion Failed: You looked up the 'patient' relationship on a 'imaging' with id 6C16C18A-1FCE-35A0-9777-47DD2F55C957 but some of the associated records were not loaded. Either make sure they are all loaded together with the parent record, or specify that the relationship is async (`DS.belongsTo({ async: true })`)

**Steps to reproduce:**
Enter a patient, enter a visit and imaging request. Don't fulfill it. Delete the patient. Go back to the imaging index route. Error!!

**Comment by jkleinsc** [comment]
Closing as all referenced issues have been resolved.
