### ISSUE TITLE
[TRACKING ISSUE] Improve dashboard by making it actually useful

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#387]
**TODO**
- [ ] Static spike of metrics view in the dash - @jglovier
- [ ] Wire up metrics
- [ ] Static spike of most commonly visited views - @jglovier
- [ ] Wire up commonly visited links
- [ ] Add help content

**Current experience:** Right now the dashboard is empty and useless (except for making you focus on the sidebar nav).

**Better experience:** Lets add some useful things to the dashboard. We could start by surfacing some metrics about your HospitalRun instance. We could show you some broad info like total number of patients, total patients checked into the hospital, available beds, inventory levels, etc. We could also show you specific metrics to your role depending on the role of the logged in user. @tangollama has defined a [list of these role based metrics here](https://github.com/HospitalRun/hospitalrun-frontend/wiki/Dashboard-Requirements).

There are also other things we could do beside metrics, like your most commonly visited views within the app, and help content.

**Mocks:**

Here are some rough concept sketches

![image](https://cloud.githubusercontent.com/assets/1319791/13921582/e8071d96-ef4e-11e5-8ab4-23296d9fa2e8.png)

**Comment by jglovier** [comment]
Just ran through some feedback from the EMR summit with @mnorbeck that verifies some of the things I've been thinking about for the dashboard lately. One of the biggest existing problems with the app is that it's too hard to get to things, and there are no shortcuts.

I think what we should do with the dashboard is create modules depending on your role (or perhaps you can customize which modules you want on the home page) that help you take actions you commonly perform. 

Are you a receptionist checking in patients all day? The home page should have the reception dashboard to quickly search for and checkin patients. Are you a lab clinician fulfilling lab requests all day? The dashboard should have quick access to the latest lab requests.

**Comment by warain** [comment]
Two ways we can achieve this is to have an activity tracker for a given staff. For example if you are a doctor, and you login, the left side of the dashboard will show activities which are being posted about your patients much like a feed, or much like a #tag, once you select and click on a patient name, you can see all the latest info posted,  (including latests labs, images ...) this could be different depending on your access levels, than you can click on a pin ( to pin the specific information you find important for that patient) once you click on that patient page, those information will populate first. 

Second thing we can do, is make sure the the elastic search appears on the top, and every single piece of data or person or lab results can be searchable (much like you already have) and once you find the patient or task, or lab (test to order) you can pin it in a non linear fashion. meaning you can x it out without it .

The problem we are having with most of the billion dollors emr syatem, is that they are too rigid.

**Comment by warain** [comment]
I could create a prototype board to show you what I mean, this is the idea I want to use for my emr system using this script as a starting point...

**Comment by jglovier** [comment]
@warain that's an interesting idea.

>I could create a prototype board to show you what I mean, this is the idea I want to use for my emr system using this script as a starting point...

Yeah, I'd love to see even a simple concept sketch of what you have in mind!

**Comment by jglovier** [comment]
See also: https://github.com/HospitalRun/design/issues/5

**Comment by fox1t** [comment]
@StefanoMiC look into this and explore what is needed for the 2.0.0
