### ISSUE TITLE
Migrate from scss-lint to stylelint

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#443]
[Scss-lint](https://github.com/brigade/scss-lint) is giving us huge value in helping keep our CSS structured, consistent, and maintainable. The huge downside for our project, however, is that it requires Ruby, and as a Node based project that makes getting started for new contributors (especially Windows devs who don't have Ruby already installed on their machine) a significant barrier.

Scss-lint does have a Node ported version, but unfortunately it doesn't support all of the linters we need, including a few of the most valuable ones.

However, there is hope. And it's name is [Stylelint](https://github.com/stylelint/stylelint). Stylelint appears to support everything that Scss-lint does, and has even more features. And best of all it is made for Node projects so it's way faster than Scss-lint (we've done some comparrison tests at GH and we are strongly considering moving from Scss-lint internally to Stylelint), and it would mean we no longer require Ruby for our app.

I'm strongly in favor of moving to Stylelint. Any objections?

cc @HospitalRun/core-maintainers

---

Notes:
- [Usage docs](http://stylelint.io/user-guide/configuration/#extends)
- [Stylelint repo](https://github.com/stylelint/stylelint)
- [Stylelint rules](http://stylelint.io/user-guide/rules/)
- [Scss-lint linters](https://github.com/brigade/scss-lint/tree/master/lib/scss_lint/linter) _(will need to port from these to Stylelint rules)_

---

**TODO**

- [ ] Install Stylelint
- [ ] Port scss-lint.yml rules to Stylelint config
- [ ] Integrate Stylelint with Travis testing
- [ ] Remove scss-lint
- [ ] Remove ember-cli-scss-lint

**Comment by jkleinsc** [comment]
@jglovier I'm fine with the change as long as it gets into the testing process with Travis.  If we move to this we will also need to remove the ember-cli-scss-lint Ember addon.

**Comment by billybonks** [comment]
Probably the best way to do this would be to build `ember-cli-style-lint` addon

**Comment by billybonks** [comment]
also https://github.com/sasstools/sass-lint which is used by https://github.com/sir-dunxalot/ember-cli-sass-lint. pure node implementation.

**Comment by jglovier** [comment]
>also https://github.com/sasstools/sass-lint which is used by https://github.com/sir-dunxalot/ember-cli-sass-lint. pure node implementation.

@jkleinsc and I looked into switching to `sass-lint` at the hack week, but unfortunately it doesn't support a few key linting rules that we're getting with `scss-lint`.

**Comment by billybonks** [comment]
so this is ready for use https://www.npmjs.com/package/ember-cli-style-lint

**Comment by jglovier** [comment]
cc @jonrohan

**Comment by jonrohan** [comment]
This is a pretty new package https://github.com/kristerkari/stylelint-scss/ that has a lot of scss specific rules for stylelint. A++ would recommend

**Comment by jglovier** [comment]
Closed in https://github.com/HospitalRun/hospitalrun-frontend/pull/488.
