### ISSUE TITLE
Internationalization long term maintenance.

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#490]
This is a tracking issue for progress of I18n maintenance task.

Since the completion of https://github.com/HospitalRun/hospitalrun-frontend/issues/141

If anyone has ideas, on how to improve translations file please ping myself or @jkleinsc 

In order to maintain internationalisations we need to:
- [x] Fail CI when pull requests use non existent translation keys. https://github.com/HospitalRun/hospitalrun-frontend/issues/492
- [x] refactor keys for `_` to `camelCase https://github.com/HospitalRun/hospitalrun-frontend/issues/573
- [ ] Translate database strings https://github.com/HospitalRun/hospitalrun-frontend/issues/549
- [x] Translate mixins https://github.com/HospitalRun/hospitalrun-frontend/issues/548
- [ ] Refactor Page Title translations https://github.com/HospitalRun/hospitalrun-frontend/issues/551
- [ ] Refactor Model property translations https://github.com/HospitalRun/hospitalrun-frontend/issues/547
- [ ] Refactor Delete message translations https://github.com/HospitalRun/hospitalrun-frontend/issues/543
- [x] Lint HTML for bare english strings https://github.com/HospitalRun/hospitalrun-frontend/issues/491 https://github.com/HospitalRun/hospitalrun-frontend/pull/505 
- [ ] Lint label property of HTMLbars https://github.com/HospitalRun/hospitalrun-frontend/issues/542 
- [ ] Prune stale translation keys https://github.com/HospitalRun/hospitalrun-frontend/issues/494
- [ ] Make sure that every page is visited during acceptance tests ( this all is required for the above task)https://github.com/HospitalRun/hospitalrun-frontend/issues/495
- [ ] Keep all translation files up to date. https://github.com/HospitalRun/hospitalrun-frontend/issues/493

**Comment by tangollama** [comment]
@billybonks I feel like we're made more progress than this. Am I wrong?

**Comment by rashad2985** [comment]
Hi @billybonks,

as a newbie contributor for this project, at the beginning, I would like to keep the translations for german and russian languages up to date till I get used to the source code of the project. Do I need to create new issue tickets for each of them?

Bests
Rashad
