### ISSUE TITLE
Translation Keys tracker

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#573]
Currently all keys in the translation file follow the `_` standard.

i.e that means that `Starte Date` would be represented by the key `start_date`. this is not a javascript convention so all keys should be changed to camel case `startDate`

Child issues will mention the namespace that needs to be changed. This is the first child key of the translation object. i.e.

```
export default {
 navigation:{
  //everything inside here is the navigation namepsace
 },
 inventory:{
  //everything inside here is the inventory namepsace
 },
```

- [x] user https://github.com/HospitalRun/hospitalrun-frontend/issues/575
- [x] admin https://github.com/HospitalRun/hospitalrun-frontend/issues/576
- [x] navigation https://github.com/HospitalRun/hospitalrun-frontend/issues/574
- [x] labels https://github.com/HospitalRun/hospitalrun-frontend/issues/577
- [x] messages https://github.com/HospitalRun/hospitalrun-frontend/issues/578
- [x] buttons https://github.com/HospitalRun/hospitalrun-frontend/issues/579
- [x] login https://github.com/HospitalRun/hospitalrun-frontend/issues/580
- [x] loading https://github.com/HospitalRun/hospitalrun-frontend/issues/581
- [x] inventory https://github.com/HospitalRun/hospitalrun-frontend/issues/582
- [x] imaging https://github.com/HospitalRun/hospitalrun-frontend/issues/583
- [x] medication https://github.com/HospitalRun/hospitalrun-frontend/issues/584
- [x] appointments https://github.com/HospitalRun/hospitalrun-frontend/issues/585
- [x] vitals https://github.com/HospitalRun/hospitalrun-frontend/issues/586
- [x] visits https://github.com/HospitalRun/hospitalrun-frontend/issues/587
- [x] labs https://github.com/HospitalRun/hospitalrun-frontend/issues/588
- [x] patients https://github.com/HospitalRun/hospitalrun-frontend/issues/589
- [x] billing https://github.com/HospitalRun/hospitalrun-frontend/issues/590
- [x] print https://github.com/HospitalRun/hospitalrun-frontend/issues/591
- [x] procedures https://github.com/HospitalRun/hospitalrun-frontend/issues/592

**Comment by jkleinsc** [comment]
@billybonks I think this issue is done.  Do you agree?

**Comment by billybonks** [comment]
@jkleinsc ye think so closing :) thanks @dapierce and @TheBanditDave
