### ISSUE TITLE
need forgot password link

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#6]
Right now if you forget your password, you are SOL. We should add a password recovery feature for users. Ideally, this would be part of the front end for users to trigger, but also something that admins could also trigger for users.
# TODO
- [ ] Create a new route 
  - [ ] ask for username (form)
  - [ ] send email with link to ask for login to the system (API call to send email)
  - [ ] changes password (update database with new password (in couch)

**Comment by richchurcher** [comment]
@tangollama I can take a look at this one.

**Comment by tangollama** [comment]
Awesome. Blossom. Please do. I'll take it off the help wanted list tomorrow. 

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by tangollama** [comment]
Removed Help Wanted as @richchurcher is looking into it.

**Comment by jglovier** [comment]
Bump. @richchurcher did you have a chance to look into this yet? Any update? When you get a PR open, feel free to cc me on it and I'll work with you on the styling.

**Comment by tangollama** [comment]
@richchurcher, I'm going to put this back in the Help Wanted pool for now. If you ping back, I'll mark as In Progress.

**Comment by richchurcher** [comment]
@tangollama I sincerely apologise for this lapse! I became crazy busy with work, and this fell off my radar entirely. I now no longer have the bandwidth to contribute as I had hoped, but best wishes for the project in the future!

**Comment by DanielDut** [comment]
I haven't even set up my dev environment for this project yet but I can look into this in the next few days. May take more than the allotted LOE because of being too busy...

**Comment by tangollama** [comment]
That's sounds great. If you want to tackle it, I'll be sure to flag it as in progress. 

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by tangollama** [comment]
@DanielDut how's this coming?

**Comment by DanielDut** [comment]
@tangollama, I have had difficulties running the project on my machine. I haven't started on it yet. I have a Windows-based PC and installing Cygwin was painfully unsuccessful. Trying it on a VM running Ubuntu is giving me build error on "Broccoli Plugin".

**Comment by tangollama** [comment]
@DanielDut any progress here? Should I move this back to Help Wanted?

**Comment by DanielDut** [comment]
@tangollama, I just got a new macbook air yesterday (just for this :) ) and setting up, let me get back to you in one week's time...

**Comment by tangollama** [comment]
@DanielDut, have you had a chance to work on this?

**Comment by tangollama** [comment]
@DanielDut any update here?

**Comment by matteddy** [comment]
@emurillo510 and I [started on this task](https://github.com/matteddy/hospitalrun-frontend/tree/add_password_recovery), and set up the necessary route. We weren't sure how to move forward without an api endpoint. 
![image](https://cloud.githubusercontent.com/assets/1839537/18802637/de460974-819e-11e6-834d-59996aab4e6b.png)
![image](https://cloud.githubusercontent.com/assets/1839537/18802655/07e65180-819f-11e6-802b-caf337730bcd.png)

**Comment by billybonks** [comment]
@matteddy i think adding a forgot password route here would work https://github.com/HospitalRun/hospitalrun-server-routes/blob/master/routes/30-auth.js.

perhaps `post '/auth/forgot'` would be an appropriate route

@jkleinsc  do you recommend a differen't route and a mailer ?

**Comment by jkleinsc** [comment]
@billybonks @matteddy yes I think putting it in the auth route makes sense and `/auth/forgot` works.  As far as a mailer, maybe https://www.npmjs.com/package/nodemailer for flexibility but I am open to other suggestions.

**Comment by EthanDavis** [comment]
Is anyone still working on this if not I would be interesting in helping out.

**Comment by broerse** [comment]
@EthanDavis I am working on a serverless solution for this on our CouchDB projects. I also use nodemailer. See my first steps: https://github.com/martinic/openwhisk-mailer
If I have all parts working it is perhaps interesting for reference.

**Comment by jkleinsc** [comment]
@EthanDavis it looks like effort on this has grown stale, so feel free to help out.  This will require two pieces - the frontend as well as code added to https://github.com/HospitalRun/hospitalrun-server-routes/blob/master/routes/30-auth.js to handle the server side (eg email).

**Comment by EthanDavis** [comment]
@jkleinsc  Okay thanks I will.

**Comment by EthanDavis** [comment]
@jkleinsc Should to forgot password link route to a new page or pull up a modal?
This might take me more than a week. I'm not super familiar with Ember. Just want to make sure.

Thanks!

**Comment by tangollama** [comment]
@EthanDavis my apologies that I didn't reply sooner. Are you still interested in this issue? If not, I'll move it back to Help Wanted.

**Comment by stukalin** [comment]
@jglovier @tangollama @jkleinsc I started working on this issue. Which email transport should we use? I've had an old sendgrid acc, will use it so far for testing purposes. Does HR have some SMTP already or can we setup sendgrid or smt similar?

**Comment by stukalin** [comment]
Oh, wait, bullshit. There should be something more clever since we are not able to share a single api key among all our users... Some kind of SMTP transport configuration each user can configure on their own. Will think about that....

**Comment by jkleinsc** [comment]
@stukalin yeah, I would make it configurable.

**Comment by stukalin** [comment]
@jglovier I double-checked and I think we still go with `nodemailer` and its default SMTP transport. Even if someone wants to use Send Grid or Mandrill or whatever, these services provide SMTP settings (at least these 2 do). So we should cover the majority of scenarios.

**Comment by sarathsoma** [comment]
@jglovier Is this still pending ? I can take this up

**Comment by stukalin** [comment]
it was pending, yes. I think I pushed my intermediate state into a branch with the corresponding name. Just look it up
