### ISSUE TITLE
Cleanup based on `ember-suave` rules

### ISSUE THREAD

**Issue by btecu** [HospitalRun/hospitalrun-frontend#732]
Continuation of #724.

**Plan**
Currently, all failing rules are turned off.
The plan is to go and fix all of the errors that the core maintainers agree on and submit those in individual (smaller) pull requests for faster merging and to avoid conflicts.

**Changes proposed**
- [x] array-bracket-spacing: `[ 1, 2 ]` -> `[1, 2]` #733
- [ ] camelcase: `some_ember_function` -> `someEmberFunction`
- [x] comma-spacing: `thing(a,b)` -> `thing(a, b)` #734
- [x] ember-suave/no-const-outside-module-scope: `const` -> `let` (inside modules) #735
- [ ] ember-suave/no-direct-property-access: `Ember.isNone()` -> `const { isNone } = Ember; isNone()` @amyrlam working on it
- [x] ember-suave/prefer-destructuring: `let brand = car.brand;` -> `let { brand } = car;` #769
- [ ] ember-suave/require-access-in-comments: most likely n/a
- [x] indent: consistent indentation (2 spaces) #772
- [x] key-spacing: `{ age:21 }` -> `{ age: 21 }` #741
- [x] keyword-spacing: `}else {` -> `} else {` #771
- [x] new-cap: `new report()` -> `new Report()` #810
- [ ] no-console: don't console log - questionable
- [x] object-curly-spacing: `{'foo': 'bar'}` -> `{ 'foo': 'bar' }` #770
- [x] object-shorthand: `doWork: function()` -> `doWork()` #809
- [x] one-var: `let a, b;` -> `let a; let b;` #736
- [x] operator-linebreak: `+` should be on the new line instead of end of previous line #773
- [x] prefer-spread: `obj.foo.apply(obj, args)` -> `foo.apply(obj, args)` #808
- [x] prefer-template `'My name is ' + name` -> ``My name is ${name}`` #745
- [x] quotes: `"` -> `'` #746
- [x] spaced-comment -> `//Comment` -> `// Comment`#739
- [x] space-infix-ops: `a+b` -> `a + b` #740

Will leave `no-console` off.

cc @HospitalRun/core-maintainers

**Comment by jkleinsc** [comment]
Thanks @btecu!

**Comment by amyrlam** [comment]
Hi, I'll take this one for now if that's ok?

> ember-suave/no-direct-property-access: Ember.isNone() -> const { isNone } = Ember; isNone()

aka remove `"disallowDirectPropertyAccess": null`

**Comment by btecu** [comment]
@amyrlam Yes, go for it. 😄

**Comment by amyrlam** [comment]
@btecu cool thanks, started a branch
