### ISSUE TITLE
[TRACKING ISSUE] Docs 1.0

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#989]
We sorely need better HospitalRun docs. Currently, we don't have any end user docs, and our developer documentation is limited.

This issue is for high level discussion and planning for our overall docs content strategy. All PR's and other issues that relate to Docs should reference this issue, and be referenced in this issue for tracking purposes.

## Scope and stages

To properly scope work on our documentation, here's a first pass at a phasing outline:

### 1. Make developer docs more comprehensive

Currently we have some basic developer documentation in the README, Contributing guide, and Wiki. But we need a more comprehensive set of developer docs. Here's a basic outline to get us started:

- [ ] Getting Started
  - [ ] Setting up your local environment
  - [ ] Ember basics for HospitalRun
- [ ] App architecture
  - [ ] Routes
  - [ ] Templates
  - [ ] Components
  - [ ] Controllers
  - [ ] Models
- [ ] Frontend
- [ ] Server
- [ ] Styleguide
  - [ ] Ember/JavaScript
  - [ ] SCSS
  - [ ] Pattern library of UI elements
- [ ] Tests

(@HospitalRun/core-maintainers feel free to edit this outline)

### 2. Publish developer docs

We need to get the developer docs into a centralized, easily accessible location. Right now they are spread apart across the [README](https://github.com/HospitalRun/hospitalrun-frontend/blob/master/README.md), [CONTRIBUTING](https://github.com/HospitalRun/hospitalrun-frontend/blob/master/.github/CONTRIBUTING.md) doc, and [wiki](https://github.com/HospitalRun/hospitalrun-frontend/wiki).

Let's get them centralized onto the Docs site. It would be great if we had a way to include them both in the frontend repo, and on the docs site (hospitalrun.io). Thinking we might be able to accomplish that with a separate repo called `/docs`, and just include that as a git submodule in both the app, and the marketing site. Thoughts on that approach?

### 3. Write end user help docs

Finally, we need a good story for end user help documentation. Ultimately I think that should be accessible directly from the application, but might also be helpful to have that available at hospitalrun.io as well. If the submodule approach works well for developer docs, perhaps we could use that approach for end user help docs too?

## Where help is needed:

We're going to need a bunch of help with this effort. Here's the shortlist that I can identify (again, @HospitalRun/core-maintainers please contribute to this list where I've left anything out, or where it could be clearer):

- [ ] we need a finalized content outline for developer docs
- [ ] we need a rough content outline for end user help docs _(perhaps @mnorbeck might be interested to take a first pass at this one?)_
- [ ] we need people to start picking sections from the above outlined docs and spike them into full articles
- [ ] we need someone to investigate and possibly setup a `/docs` and `/user-help` repo as git submodules
- [ ] we'll need design for how the docs will appear on the hospitalrun.io site
- [ ] we'll need design for how the docs will appear in the app
- [ ] we should start breaking this tracking issue out into smaller scoped issues that we can reference from here

---

cc @HospitalRun/core-maintainers

**Comment by dasManaswini** [comment]
@jglovier @jkleinsc  I would like to add a piece of documentation for docker compose referring the PR #1015 which is already merged.There is a discrepancy in the contribution.md and the installation guide regarding the installation process.I would like to make necessary changes over there too.Should I make different PR for both of it?

**Comment by jkleinsc** [comment]
@dasManaswini you can combine those into one PR.
